services:
  web:
    build: .
    command: /app/start.sh
    volumes:
      - .:/app
    ports:
      - "8000:3000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - PORT=3000
    env_file:
      - .env
