[phases.setup]
nixPkgs = [
  "python311",
  "pkg-config",
  "mariadb-connector-c",
  "mysql80", # provides correct mysqlclient.pc
  "gcc",
  "gnumake"
]

[phases.install]
env = {
  PKG_CONFIG_PATH = "${PKG_CONFIG_PATH:-}/nix/store/*-mysql80-*/lib/pkgconfig"
}
cmds = [
  "python -m venv venv",
  ". venv/bin/activate && pip install --upgrade pip",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". venv/bin/activate && gunicorn backend.wsgi:application --bind 0.0.0.0:${PORT:-8000}"
