[phases.setup]
nixPkgs = [
  "python311",
  "pkg-config",
  "mysql80",
  "gcc",
  "gnumake"
]

[phases.install]
env = { 
  PKG_CONFIG_PATH = "/nix/store" 
}
cmds = [
  "python -m venv venv",
  ". venv/bin/activate && pip install --upgrade pip",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". venv/bin/activate && gunicorn backend.wsgi:application --bind 0.0.0.0:${PORT:-8000}"
