services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: REDIS_URL
        value: redis://red-d0lj2gnfte5s739isplg:6379
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend worker -l info --concurrency=2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: REDIS_URL
        value: redis://red-d0lj2gnfte5s739isplg:6379
      - key: PYTHONUNBUFFERED
        value: "1"
