services:
  - type: web
    name: nachos-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: REDIS_URL
        value: redis://red-d0lj2gnfte5s739isplg:6379
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
