# Generated by Django 5.2 on 2025-04-22 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecommunity',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userwatchedmovie',
            name='watch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
